a.out : *.cpp
	g++ *.cpp

move_easy:
	mv *.cpp ./Easy/
	make clean
	clear

move_med : 
	mv *.cpp ./Medium/
	make clean
	clear

move_hard :
	mv *.cpp ./Hard
	make clean
	clear

clean : 
	rm *.out
	clear
